workflows:
  android_aab:
    name: Android AAB
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ROUTE_ID: riga_cocktail_v1
    scripts:
      - cd drink_story
      - flutter --version
      - flutter pub get
      # Подготовка keystore из переменных окружения приложения
      - |
        echo "→ prepare Android keystore (if present)"
        if [ -n "$ANDROID_KEYSTORE_B64" ]; then
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_B64" | base64 -d > android/app/keystore.jks
          cat > android/key.properties <<EOF
storePassword=$KEYSTORE_PASSWORD
keyPassword=$KEY_PASSWORD
keyAlias=$KEY_ALIAS
storeFile=app/keystore.jks
EOF
        else
          echo "WARN: ANDROID_KEYSTORE_B64 is empty — release may be unsigned"
        fi
      - |
        set -e
        flutter build appbundle --release \
          --dart-define=DEMO_PACKAGE_URL=$DEMO_PACKAGE_URL \
          --dart-define=DEMO_PACKAGE_SHA256=$DEMO_PACKAGE_SHA256 \
          --dart-define=ROUTE_ID=$ROUTE_ID \
          ${API_BASE:+--dart-define=API_BASE=$API_BASE}
    artifacts:
      - drink_story/build/app/outputs/bundle/release/*.aab

  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        ROUTE_ID: riga_cocktail_v1
    scripts:
      - cd drink_story
      - flutter --version
      - flutter pub get
      - |
        set -e
        flutter build ipa --release \
          --dart-define=DEMO_PACKAGE_URL=$DEMO_PACKAGE_URL \
          --dart-define=DEMO_PACKAGE_SHA256=$DEMO_PACKAGE_SHA256 \
          --dart-define=ROUTE_ID=$ROUTE_ID \
          ${API_BASE:+--dart-define=API_BASE=$API_BASE}
    artifacts:
      - drink_story/build/ios/ipa/*.ipa
    # publishing можно включить позже, когда добавите iOS-секреты на уровне приложения
